# Cloudflare Pages configuration for Xpenses frontend
[build]
  command = "npm run build"
  destination = "build"

[build.environment]
  NODE_VERSION = "18"

# API redirects to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://xpsense-production.up.railway.app/api/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
