# Cloudflare Workers configuration for Xpenses backend
name = "xpenses-backend"
main = "backend/dist/app.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "xpenses-backend-prod"

[env.staging]
name = "xpenses-backend-staging"

# Environment variables (secrets should be set via Cloudflare dashboard)
[vars]
NODE_ENV = "production"
LOG_LEVEL = "info"
